name: Base
logging: True
unlabeled: True

model:
    pretrained: True

data:
    path: /tmp
    num_classes: 10

param:
    lr: 5e-4
    batch_size: 2_048

trainer:
    max_steps: 100_000
    check_val_every_n_epoch: 10

logger:
    project: autoencoder-base