defaults:
    - base

name: VAE MNIST
logging: true

data:
    name: moving_mnist
    num_classes: 10
    shape: [1, 64, 64]
    seq_len: 20
    deterministic: true

model:
    rec_loss: false
    ae:
        latent_dim: 128
        checkpoint: null
    lstm:
        hidden_dim: 256
        num_layers: 2
        skip: true

param:
    lr: 2e-3
    batch_size: 128

trainer:
    max_steps: 100_000
    check_val_every_n_epoch: 1

logger:
    project: vae-lstm-moving-mnist