defaults:
    - base

name: VAE MNIST
logging: true

data:
    name: static_mnist
    num_classes: 10
    shape: [1, 64, 64]

param:
    lr: 3e-3
    batch_size: 128
    latent_dim: 64

trainer:
    max_steps: 100_000
    check_val_every_n_epoch: 1

logger:
    project: vae-lstm-moving-mnist